app_name: Wave
port: 8300
redis:
  host: 106.186.114.114
  port: 6379
  key_prefix: 'ranaly:'
users:
  - username: Wave-Team
    password: ping55555
    role: 0
pages:
  - title: PP
    widgets:
      - type: amount_today_count
        bucket: [pp:message:success, pp:reply:success, pp:push:success]
        title: statistics
      - type: amount_line_chart
        bucket: [pp:message:success, pp:message:failure]
        title: message
      - type: amount_line_chart
        bucket: [pp:reply:success, pp:reply:failure]
        title: reply
      - type: amount_line_chart
        bucket: [pp:push:success, pp:push:failure]
        title: push
  - title: Tower
    widgets:
      - type: amount_line_chart
        bucket: tower:xxx
        title: xxx
      - type: amount_line_chart
        bucket: tower:yyy
        title: yyy