app_name: Wave
port: 8300
redis:
  host: 106.186.114.114
  port: 6379
  key_prefix: 'ranaly:'
users:
  - username: 1
    password: 1
    role: 0
pages:
  - title: PP
    widgets:
      - type: amount_today_count
        bucket: [pp:message:success, pp:reply:success, pp:push:success]
        title: 数据统计
      - type: amount_line_chart
        bucket: [pp:message:success, pp:message:failure]
        title: 发送邮件
      - type: amount_line_chart
        bucket: [pp:reply:success, pp:reply:failure]
        title: 回复邮件
      - type: amount_line_chart
        bucket: [pp:push:success, pp:push:failure]
        title: 推送
  - title: Tower
    widgets:
      - type: amount_line_chart
        bucket: tower:xxx
        title: xxx
      - type: amount_line_chart
        bucket: tower:yyy
        title: yyy